# Site settings
title: WebJeda | A modern web development blog
description: "WebJeda is a company oriented towards building modern websites and apps. It also provides smart hosting solutions. Contact us for modern, fast and responsive websites"
url: http://blog.webjeda.com
author: 
  twitter: sharathdt
twitter:
   site: webjeda

logo: /img/webjeda-logo.svg
#image: {{page.image}}
facebook: https://www.facebook.com/webjeda
twitter: https://twitter.com/webjeda
github: https://github.com/sharu725
youtube: https://www.youtube.com/channel/UCbOO7d0vVo0kIrkd7m32irg
email: mailto:hello@webjeda.com
feedburner-subscribe: https://feedburner.google.com/fb/a/mailverify?uri=webjedablog&amp;loc=en_US 
analytics: 'UA-71358787-1'
disqus-shortname: webjeda
copyrights-owner: WebJeda # Copyright in the footer
feedly: http://cloud.feedly.com/#subscription%2Ffeed%2Fhttp%3A%2F%2Fblog.webjeda.com%2Ffeed.xml

#super-proxy: 'https://rugged-sunbeam-127917.appspot.com/query?id=ahdzfnJ1Z2dlZC1zdW5iZWFtLTEyNzkxN3IVCxIIQXBpUXVlcnkYgICAgLzLigoM&format=json'

# Build settings
#baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
#source: .
destination: ./_site
permalink: /:title/
paginate: 6
paginate_path: /page:num/
highlighter: rouge
      
sass:
    style: compressed

  
#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
  
#collection
collections:
    jekyll-themes:
        output: true




gems: [jekyll-paginate, jemoji, jekyll-seo-tag]